# ***Products***

## ***Đọc dữ liệu và gộp dữ liệu***

In [158]:
import pandas as pd
import numpy as np

df_innerwear = pd.read_csv('uniqlo_women_innerwear.csv', sep=';')
df_innerwear.head()

,category,product_url,Product Name,Gender,Size,Price,Rate,Number_of_rates,Description,Chất liệu,Hướng dẫn giặt,Mã sản phẩm,img_url
0,innerwear,https://www.uniqlo.com/vn/vi/products/E457911-000,AIRism Áo Hai Dây,Nữ,XS-XXL,244.0,4.7,50,Màu sắc Màu sắc Màu sắc NỮ XS-XXL AIRism Áo Ha...,"65% Nylon, 25% Cupro, 10% Elastan ( 47% Sử Dụn...","Giặt máy nước lạnh, giặt nhẹ, Không giặt khô, ...",474002,https://image.uniqlo.com/UQ/ST3/vn/imagesgoods...
1,innerwear,https://www.uniqlo.com/vn/vi/products/E457912-000,AIRism Áo Không Tay,Nữ,XS-XXL,244.0,4.9,111,Màu sắc Màu sắc Màu sắc Màu sắc Màu sắc NỮ XS-...,"65% Nylon, 25% Cupro, 10% Elastan ( 47% Sử Dụn...","Giặt máy nước lạnh, giặt nhẹ, Không giặt khô, ...",482150,https://image.uniqlo.com/UQ/ST3/vn/imagesgoods...
2,innerwear,https://www.uniqlo.com/vn/vi/products/E473979-000,AIRism Áo Bra Top | Không Tay,Nữ,XS-XXL,489.0,4.9,303,Màu sắc Màu sắc Màu sắc Màu sắc Màu sắc NỮ XS-...,"Vải Chính: 67% Polyeste, 24% Cupro, 9% Elastan...","Giặt máy nước lạnh, giặt nhẹ, Không giặt khô, ...",482181,https://image.uniqlo.com/UQ/ST3/vn/imagesgoods...
3,innerwear,https://www.uniqlo.com/vn/vi/products/E481036-000,Quần Short Định Hình,Nữ,M-XL,293.0,4.8,30,Màu sắc NỮ M-XL Quần Short Định Hình VND 293.0...,"Thân: 72% Nylon, 28% Elastan ( 36% Sử Dụng Sợi...","Giặt máy nước lạnh, giặt nhẹ, Không giặt khô, ...",481036,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
4,innerwear,https://www.uniqlo.com/vn/vi/products/E480785-000,AIRism Quần Lót Định Hình | Định Hình Vùng Bụng,Nữ,L,293.0,4.7,14,Màu sắc NỮ L AIRism Quần Lót Định Hình | Định ...,"Thân: 72% Nylon, 28% Elastan/ Eo: 60% Nylon, 4...","Giặt máy nước lạnh, giặt nhẹ, Không giặt khô, ...",480886,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...

In [159]:
import pandas as pd

# Lấy danh sách các file bắt đầu bằng uniqlo_women_ và kết thúc .csv
files = ["uniqlo_women_accessories.csv", 
         "uniqlo_women_bottoms.csv", 
         "uniqlo_women_outerwear.csv",
         "uniqlo_women_loungewear-and-homewear.csv",
         "uniqlo_women_shirts-and-blouses.csv",
         "uniqlo_women_skirts-and-dresses.csv",
         "uniqlo_women_sweaters-and-knitwear.csv",
         "uniqlo_women_t-shirts-sweat-and-fleece.csv",
         "uniqlo_men_accessories.csv", 
         "uniqlo_men_bottoms.csv", 
         "uniqlo_men_innerwear.csv", 
         "uniqlo_men_outerwear.csv",
         "uniqlo_men_loungewear-and-homewear.csv",
         "uniqlo_men_linen.csv",
         "uniqlo_men_special-collaboration.csv",
         "uniqlo_men_uv-protection.csv",
         "uniqlo_men_shirts-and-polo-shirts.csv",
         "uniqlo_men_sweaters-and-knitwear.csv",
         "uniqlo_men_t-shirts-sweat-and-fleece.csv"]

# Đọc và gộp các file
df_list = [pd.read_csv(file) for file in files]
df_merged = pd.concat(df_list, ignore_index=True)
df_merged = pd.concat([df_merged, df_innerwear], ignore_index=True)

df_merged.head()

,category,product_url,Product Name,Gender,Size,Price,Rate,Number_of_rates,Description,Chất liệu,Hướng dẫn giặt,Mã sản phẩm,img_url
0,accessories,https://www.uniqlo.com/vn/vi/products/E481610-000,Túi Bán Nguyệt Mini Đeo Chéo,Unisex,One,293.000,5.0,93,Colour Colour Colour Colour Colour Colour Colo...,Vải Ngoài: 100% Nylon ( 100% Sử Dụng Sợi Nylon...,"Không giặt, Không giặt khô, Không sấy khô",481610,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
1,accessories,https://www.uniqlo.com/vn/vi/products/E478708-000,Túi Bán Nguyệt Mini Đeo Chéo,Unisex,One,293.000,5.0,327,Colour Colour UNISEX One Size Túi Bán Nguyệt M...,Vải Chính: 100% Nylon ( 100% Sử Dụng Sợi Nylon...,"Không giặt, Không giặt khô, Không sấy khô",478708,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
2,accessories,https://www.uniqlo.com/vn/vi/products/E481359-000,Ba Lô Đa Tính Năng,Unisex,One,1.471.000,5.0,5,Colour UNISEX One Size Ba Lô Đa Tính Năng VND ...,Vải Chính: Thân: Đế: 100% Polyeste/ Mắt Lưới: ...,"Không giặt, Không giặt khô, Không sấy khô",481359,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
3,accessories,https://www.uniqlo.com/vn/vi/products/E478321-000,Balo Nhiều Ngăn,Unisex,One,980.000,5.0,64,Colour UNISEX One Size Balo Nhiều Ngăn VND 980...,Vải Chính: Thân: 100% Nylon/ Mắt Lưới: 100% Po...,"Không giặt, Không giặt khô, Không sấy khô",478321,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
4,accessories,https://www.uniqlo.com/vn/vi/products/E483050-000,Túi Dây Rút,Nữ,One,588.000,5.0,8,Colour Colour Colour Colour NỮ One Size Túi Dâ...,Shell: Vải Túi Trong: 100% Polyeste/ Lớp Lót: ...,"Không giặt, Không giặt khô, Không sấy khô",483050,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...

In [160]:
df_merged.isna().sum()

category             0
product_url          0
Product Name         0
Gender               0
Size                 0
Price                0
Rate               109
Number_of_rates      0
Description          0
Chất liệu            5
Hướng dẫn giặt       5
Mã sản phẩm          0
img_url              4
dtype: int64

## ***Xử lý thuộc tính Price***

In [161]:
df_merged['Price'] = df_merged['Price'].astype(str).str.replace('.', '', regex=False).str.strip()
df_merged['Price'] = pd.to_numeric(df_merged['Price'], errors='coerce')
df_merged

,category,product_url,Product Name,Gender,Size,Price,Rate,Number_of_rates,Description,Chất liệu,Hướng dẫn giặt,Mã sản phẩm,img_url
0,accessories,https://www.uniqlo.com/vn/vi/products/E481610-000,Túi Bán Nguyệt Mini Đeo Chéo,Unisex,One,293000,5.0,93,Colour Colour Colour Colour Colour Colour Colo...,Vải Ngoài: 100% Nylon ( 100% Sử Dụng Sợi Nylon...,"Không giặt, Không giặt khô, Không sấy khô",481610,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
1,accessories,https://www.uniqlo.com/vn/vi/products/E478708-000,Túi Bán Nguyệt Mini Đeo Chéo,Unisex,One,293000,5.0,327,Colour Colour UNISEX One Size Túi Bán Nguyệt M...,Vải Chính: 100% Nylon ( 100% Sử Dụng Sợi Nylon...,"Không giặt, Không giặt khô, Không sấy khô",478708,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
2,accessories,https://www.uniqlo.com/vn/vi/products/E481359-000,Ba Lô Đa Tính Năng,Unisex,One,1471000,5.0,5,Colour UNISEX One Size Ba Lô Đa Tính Năng VND ...,Vải Chính: Thân: Đế: 100% Polyeste/ Mắt Lưới: ...,"Không giặt, Không giặt khô, Không sấy khô",481359,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
3,accessories,https://www.uniqlo.com/vn/vi/products/E478321-000,Balo Nhiều Ngăn,Unisex,One,980000,5.0,64,Colour UNISEX One Size Balo Nhiều Ngăn VND 980...,Vải Chính: Thân: 100% Nylon/ Mắt Lưới: 100% Po...,"Không giặt, Không giặt khô, Không sấy khô",478321,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
4,accessories,https://www.uniqlo.com/vn/vi/products/E483050-000,Túi Dây Rút,Nữ,One,588000,5.0,8,Colour Colour Colour Colour NỮ One Size Túi Dâ...,Shell: Vải Túi Trong: 100% Polyeste/ Lớp Lót: ...,"Không giặt, Không giặt khô, Không sấy khô",483050,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
976,innerwear,https://www.uniqlo.com/vn/vi/products/E473953-000,Tất | 3 Đôi,Nữ,23-25cm,1950,5.0,4,Màu sắc Màu sắc Màu sắc Màu sắc Màu sắc Màu sắ...,"64% Bông, 34% Nylon, 2% Elastan","Giặt máy nước lạnh, Không giặt khô, Không sấy khô",482720,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
977,innerwear,https://www.uniqlo.com/vn/vi/products/E467421-000,NỮ TẤT,Nữ,23-25cm,1950,5.0,5,Màu sắc Màu sắc Màu sắc Màu sắc Màu sắc NỮ 23-...,"82% Bông, 15% Polyeste, 2% Elastan, 1% Nylon","Giặt máy nước lạnh, Không giặt khô, Không sấy khô",482725,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
978,innerwear,https://www.uniqlo.com/vn/vi/products/E460431-000,Tất | 3 Đôi | Vải Gân,Nữ,23-25cm,1950,5.0,4,Màu sắc Màu sắc Màu sắc Màu sắc NỮ 23-25cm Tất...,"66% Bông, 17% Polyeste, 15% Nylon, 2% Elastan","Giặt máy nước lạnh, Không giặt khô, Không sấy khô",482724,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
979,innerwear,https://www.uniqlo.com/vn/vi/products/E482148-000,AIRism Áo Hai Dây,Nữ,S-XL,2440,NaN,0,Màu sắc Màu sắc Màu sắc Màu sắc Màu sắc NỮ S-X...,"65% Nylon, 25% Cupro, 10% Elastan ( 47% Sử Dụn...","Giặt máy nước lạnh, giặt nhẹ, Không giặt khô, ...",482148,https://image.uniqlo.com/UQ/ST3/vn/imagesgoods...
980,innerwear,https://www.uniqlo.com/vn/vi/products/E484407-000,Tất | 3 Đôi,Nữ,23-25cm,1950,5.0,1,Màu sắc Màu sắc Màu sắc Màu sắc Màu sắc NỮ 23-...,"82% Bông, 13% Polyeste, 3% Nylon, 2% Elastan","Giặt máy nước lạnh, Không giặt khô, Không sấy khô",484407,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...

In [162]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 981 entries, 0 to 980
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   category         981 non-null    object
 1   product_url      981 non-null    object
 2   Product Name     981 non-null    object
 3   Gender           981 non-null    object
 4   Size             981 non-null    object
 5   Price            981 non-null    int64
 6   Rate             872 non-null    float64
 7   Number_of_rates  981 non-null    int64
 8   Description      981 non-null    object
 9   Chất liệu        976 non-null    object
 10  Hướng dẫn giặt   976 non-null    object
 11  Mã sản phẩm      981 non-null    object
 12  img_url          977 non-null    object
dtypes: float64(1), int64(2), object(10)
memory usage: 99.8+ KB

In [163]:
df_merged.isna().sum()

category             0
product_url          0
Product Name         0
Gender               0
Size                 0
Price                0
Rate               109
Number_of_rates      0
Description          0
Chất liệu            5
Hướng dẫn giặt       5
Mã sản phẩm          0
img_url              4
dtype: int64

In [164]:
def adjust_price(price):
    if 1000 <= price < 10000:
        return price * 100
    return price

df_merged['Price'] = df_merged['Price'].apply(adjust_price)
df_merged.isna().sum()

category             0
product_url          0
Product Name         0
Gender               0
Size                 0
Price                0
Rate               109
Number_of_rates      0
Description          0
Chất liệu            5
Hướng dẫn giặt       5
Mã sản phẩm          0
img_url              4
dtype: int64

## ***Loại bỏ giá trị trùng lặp***

In [165]:
duplicates_mask = df_merged.duplicated(subset=['Product Name'], keep='first')
removed_product_duplicate = df_merged.loc[duplicates_mask, 'Mã sản phẩm'].unique().tolist()
df_merged = df_merged.drop_duplicates(subset=['Product Name'], keep='first')
df_merged

,category,product_url,Product Name,Gender,Size,Price,Rate,Number_of_rates,Description,Chất liệu,Hướng dẫn giặt,Mã sản phẩm,img_url
0,accessories,https://www.uniqlo.com/vn/vi/products/E481610-000,Túi Bán Nguyệt Mini Đeo Chéo,Unisex,One,293000,5.0,93,Colour Colour Colour Colour Colour Colour Colo...,Vải Ngoài: 100% Nylon ( 100% Sử Dụng Sợi Nylon...,"Không giặt, Không giặt khô, Không sấy khô",481610,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
2,accessories,https://www.uniqlo.com/vn/vi/products/E481359-000,Ba Lô Đa Tính Năng,Unisex,One,1471000,5.0,5,Colour UNISEX One Size Ba Lô Đa Tính Năng VND ...,Vải Chính: Thân: Đế: 100% Polyeste/ Mắt Lưới: ...,"Không giặt, Không giặt khô, Không sấy khô",481359,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
3,accessories,https://www.uniqlo.com/vn/vi/products/E478321-000,Balo Nhiều Ngăn,Unisex,One,980000,5.0,64,Colour UNISEX One Size Balo Nhiều Ngăn VND 980...,Vải Chính: Thân: 100% Nylon/ Mắt Lưới: 100% Po...,"Không giặt, Không giặt khô, Không sấy khô",478321,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
4,accessories,https://www.uniqlo.com/vn/vi/products/E483050-000,Túi Dây Rút,Nữ,One,588000,5.0,8,Colour Colour Colour Colour NỮ One Size Túi Dâ...,Shell: Vải Túi Trong: 100% Polyeste/ Lớp Lót: ...,"Không giặt, Không giặt khô, Không sấy khô",483050,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
5,accessories,https://www.uniqlo.com/vn/vi/products/E481663-000,Túi Puffy,Nữ,One,588000,4.6,5,Colour Colour Colour NỮ One Size Túi Puffy VND...,Shell: 100% Polyeste/ Lớp Độn: 100% Polyeste/ ...,"Không giặt, Không giặt khô, Không sấy khô",481663,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
971,innerwear,https://www.uniqlo.com/vn/vi/products/E485207-000,Tất | 3 Đôi,Nữ,23-25cm,195000,195.0,0,Màu sắc Màu sắc NỮ 23-25cm Tất | 3 Đôi VND 195...,"82% Bông, 12% Nylon, 3% Polyeste, 3% Elastan","Giặt máy nước lạnh, Không giặt khô, Không sấy khô",485207,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
974,innerwear,https://www.uniqlo.com/vn/vi/products/E482729-000,Tất | 3 Đôi | Ribbed Line,Nữ,23-25cm,195000,195.0,0,Màu sắc Màu sắc NỮ 23-25cm Tất | 3 Đôi | Ribbe...,"65% Bông, 16% Polyeste, 16% Nylon, 3% Elastan","Giặt máy nước lạnh, Không giặt khô, Không sấy khô",482729,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
975,innerwear,https://www.uniqlo.com/vn/vi/products/E482722-000,Tất | 3 Đôi | Crew Taper,Nữ,23-25cm,195000,195.0,0,Màu sắc Màu sắc NỮ 23-25cm Tất | 3 Đôi | Crew ...,"48% Polyeste, 48% Nylon, 4% Elastan ( 42% Sử D...","Giặt máy nước lạnh, Không giặt khô, Không sấy khô",482722,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
977,innerwear,https://www.uniqlo.com/vn/vi/products/E467421-000,NỮ TẤT,Nữ,23-25cm,195000,5.0,5,Màu sắc Màu sắc Màu sắc Màu sắc Màu sắc NỮ 23-...,"82% Bông, 15% Polyeste, 2% Elastan, 1% Nylon","Giặt máy nước lạnh, Không giặt khô, Không sấy khô",482725,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
978,innerwear,https://www.uniqlo.com/vn/vi/products/E460431-000,Tất | 3 Đôi | Vải Gân,Nữ,23-25cm,195000,5.0,4,Màu sắc Màu sắc Màu sắc Màu sắc NỮ 23-25cm Tất...,"66% Bông, 17% Polyeste, 15% Nylon, 2% Elastan","Giặt máy nước lạnh, Không giặt khô, Không sấy khô",482724,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...

In [166]:
df_merged = df_merged.reset_index(drop = True)
df = df_merged.copy()

## ***Xử lý thuộc tính Description***

In [167]:
df['Description'] = df['Description'].replace('Màu sắc ', '', regex=True)
df['Description'] = df['Description'].replace('Colour ', '', regex=True)
df

,category,product_url,Product Name,Gender,Size,Price,Rate,Number_of_rates,Description,Chất liệu,Hướng dẫn giặt,Mã sản phẩm,img_url
0,accessories,https://www.uniqlo.com/vn/vi/products/E481610-000,Túi Bán Nguyệt Mini Đeo Chéo,Unisex,One,293000,5.0,93,UNISEX One Size Túi Bán Nguyệt Mini Đeo Chéo V...,Vải Ngoài: 100% Nylon ( 100% Sử Dụng Sợi Nylon...,"Không giặt, Không giặt khô, Không sấy khô",481610,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
1,accessories,https://www.uniqlo.com/vn/vi/products/E481359-000,Ba Lô Đa Tính Năng,Unisex,One,1471000,5.0,5,UNISEX One Size Ba Lô Đa Tính Năng VND 1.471.0...,Vải Chính: Thân: Đế: 100% Polyeste/ Mắt Lưới: ...,"Không giặt, Không giặt khô, Không sấy khô",481359,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
2,accessories,https://www.uniqlo.com/vn/vi/products/E478321-000,Balo Nhiều Ngăn,Unisex,One,980000,5.0,64,UNISEX One Size Balo Nhiều Ngăn VND 980.000 5....,Vải Chính: Thân: 100% Nylon/ Mắt Lưới: 100% Po...,"Không giặt, Không giặt khô, Không sấy khô",478321,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
3,accessories,https://www.uniqlo.com/vn/vi/products/E483050-000,Túi Dây Rút,Nữ,One,588000,5.0,8,NỮ One Size Túi Dây Rút VND 588.000 New 5.0 (8),Shell: Vải Túi Trong: 100% Polyeste/ Lớp Lót: ...,"Không giặt, Không giặt khô, Không sấy khô",483050,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
4,accessories,https://www.uniqlo.com/vn/vi/products/E481663-000,Túi Puffy,Nữ,One,588000,4.6,5,NỮ One Size Túi Puffy VND 588.000 New 4.6 (5),Shell: 100% Polyeste/ Lớp Độn: 100% Polyeste/ ...,"Không giặt, Không giặt khô, Không sấy khô",481663,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
480,innerwear,https://www.uniqlo.com/vn/vi/products/E485207-000,Tất | 3 Đôi,Nữ,23-25cm,195000,195.0,0,NỮ 23-25cm Tất | 3 Đôi VND 195.000 New,"82% Bông, 12% Nylon, 3% Polyeste, 3% Elastan","Giặt máy nước lạnh, Không giặt khô, Không sấy khô",485207,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
481,innerwear,https://www.uniqlo.com/vn/vi/products/E482729-000,Tất | 3 Đôi | Ribbed Line,Nữ,23-25cm,195000,195.0,0,NỮ 23-25cm Tất | 3 Đôi | Ribbed Line VND 195.0...,"65% Bông, 16% Polyeste, 16% Nylon, 3% Elastan","Giặt máy nước lạnh, Không giặt khô, Không sấy khô",482729,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
482,innerwear,https://www.uniqlo.com/vn/vi/products/E482722-000,Tất | 3 Đôi | Crew Taper,Nữ,23-25cm,195000,195.0,0,NỮ 23-25cm Tất | 3 Đôi | Crew Taper VND 195.00...,"48% Polyeste, 48% Nylon, 4% Elastan ( 42% Sử D...","Giặt máy nước lạnh, Không giặt khô, Không sấy khô",482722,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
483,innerwear,https://www.uniqlo.com/vn/vi/products/E467421-000,NỮ TẤT,Nữ,23-25cm,195000,5.0,5,NỮ 23-25cm NỮ TẤT VND 195.000 New 5.0 (5),"82% Bông, 15% Polyeste, 2% Elastan, 1% Nylon","Giặt máy nước lạnh, Không giặt khô, Không sấy khô",482725,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
484,innerwear,https://www.uniqlo.com/vn/vi/products/E460431-000,Tất | 3 Đôi | Vải Gân,Nữ,23-25cm,195000,5.0,4,NỮ 23-25cm Tất | 3 Đôi | Vải Gân VND 195.000 N...,"66% Bông, 17% Polyeste, 15% Nylon, 2% Elastan","Giặt máy nước lạnh, Không giặt khô, Không sấy khô",482724,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...

## ***Xử lý thuộc tính Size***

In [168]:
df['Size'] = df['Size'].replace('One', 'One Size', regex=True)
df

,category,product_url,Product Name,Gender,Size,Price,Rate,Number_of_rates,Description,Chất liệu,Hướng dẫn giặt,Mã sản phẩm,img_url
0,accessories,https://www.uniqlo.com/vn/vi/products/E481610-000,Túi Bán Nguyệt Mini Đeo Chéo,Unisex,One Size,293000,5.0,93,UNISEX One Size Túi Bán Nguyệt Mini Đeo Chéo V...,Vải Ngoài: 100% Nylon ( 100% Sử Dụng Sợi Nylon...,"Không giặt, Không giặt khô, Không sấy khô",481610,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
1,accessories,https://www.uniqlo.com/vn/vi/products/E481359-000,Ba Lô Đa Tính Năng,Unisex,One Size,1471000,5.0,5,UNISEX One Size Ba Lô Đa Tính Năng VND 1.471.0...,Vải Chính: Thân: Đế: 100% Polyeste/ Mắt Lưới: ...,"Không giặt, Không giặt khô, Không sấy khô",481359,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
2,accessories,https://www.uniqlo.com/vn/vi/products/E478321-000,Balo Nhiều Ngăn,Unisex,One Size,980000,5.0,64,UNISEX One Size Balo Nhiều Ngăn VND 980.000 5....,Vải Chính: Thân: 100% Nylon/ Mắt Lưới: 100% Po...,"Không giặt, Không giặt khô, Không sấy khô",478321,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
3,accessories,https://www.uniqlo.com/vn/vi/products/E483050-000,Túi Dây Rút,Nữ,One Size,588000,5.0,8,NỮ One Size Túi Dây Rút VND 588.000 New 5.0 (8),Shell: Vải Túi Trong: 100% Polyeste/ Lớp Lót: ...,"Không giặt, Không giặt khô, Không sấy khô",483050,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
4,accessories,https://www.uniqlo.com/vn/vi/products/E481663-000,Túi Puffy,Nữ,One Size,588000,4.6,5,NỮ One Size Túi Puffy VND 588.000 New 4.6 (5),Shell: 100% Polyeste/ Lớp Độn: 100% Polyeste/ ...,"Không giặt, Không giặt khô, Không sấy khô",481663,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
480,innerwear,https://www.uniqlo.com/vn/vi/products/E485207-000,Tất | 3 Đôi,Nữ,23-25cm,195000,195.0,0,NỮ 23-25cm Tất | 3 Đôi VND 195.000 New,"82% Bông, 12% Nylon, 3% Polyeste, 3% Elastan","Giặt máy nước lạnh, Không giặt khô, Không sấy khô",485207,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
481,innerwear,https://www.uniqlo.com/vn/vi/products/E482729-000,Tất | 3 Đôi | Ribbed Line,Nữ,23-25cm,195000,195.0,0,NỮ 23-25cm Tất | 3 Đôi | Ribbed Line VND 195.0...,"65% Bông, 16% Polyeste, 16% Nylon, 3% Elastan","Giặt máy nước lạnh, Không giặt khô, Không sấy khô",482729,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
482,innerwear,https://www.uniqlo.com/vn/vi/products/E482722-000,Tất | 3 Đôi | Crew Taper,Nữ,23-25cm,195000,195.0,0,NỮ 23-25cm Tất | 3 Đôi | Crew Taper VND 195.00...,"48% Polyeste, 48% Nylon, 4% Elastan ( 42% Sử D...","Giặt máy nước lạnh, Không giặt khô, Không sấy khô",482722,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
483,innerwear,https://www.uniqlo.com/vn/vi/products/E467421-000,NỮ TẤT,Nữ,23-25cm,195000,5.0,5,NỮ 23-25cm NỮ TẤT VND 195.000 New 5.0 (5),"82% Bông, 15% Polyeste, 2% Elastan, 1% Nylon","Giặt máy nước lạnh, Không giặt khô, Không sấy khô",482725,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
484,innerwear,https://www.uniqlo.com/vn/vi/products/E460431-000,Tất | 3 Đôi | Vải Gân,Nữ,23-25cm,195000,5.0,4,NỮ 23-25cm Tất | 3 Đôi | Vải Gân VND 195.000 N...,"66% Bông, 17% Polyeste, 15% Nylon, 2% Elastan","Giặt máy nước lạnh, Không giặt khô, Không sấy khô",482724,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...

## ***Xử lý thuộc tính rate***

In [169]:
df['Rate'] = pd.to_numeric(df['Rate'], errors='coerce')
condition = (df['Rate'] > 5) | (df['Rate'].isna())
dropped_product_rate = df.loc[condition, 'Mã sản phẩm'].unique().tolist()
df = df[~condition].reset_index(drop=True)
df

,category,product_url,Product Name,Gender,Size,Price,Rate,Number_of_rates,Description,Chất liệu,Hướng dẫn giặt,Mã sản phẩm,img_url
0,accessories,https://www.uniqlo.com/vn/vi/products/E481610-000,Túi Bán Nguyệt Mini Đeo Chéo,Unisex,One Size,293000,5.0,93,UNISEX One Size Túi Bán Nguyệt Mini Đeo Chéo V...,Vải Ngoài: 100% Nylon ( 100% Sử Dụng Sợi Nylon...,"Không giặt, Không giặt khô, Không sấy khô",481610,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
1,accessories,https://www.uniqlo.com/vn/vi/products/E481359-000,Ba Lô Đa Tính Năng,Unisex,One Size,1471000,5.0,5,UNISEX One Size Ba Lô Đa Tính Năng VND 1.471.0...,Vải Chính: Thân: Đế: 100% Polyeste/ Mắt Lưới: ...,"Không giặt, Không giặt khô, Không sấy khô",481359,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
2,accessories,https://www.uniqlo.com/vn/vi/products/E478321-000,Balo Nhiều Ngăn,Unisex,One Size,980000,5.0,64,UNISEX One Size Balo Nhiều Ngăn VND 980.000 5....,Vải Chính: Thân: 100% Nylon/ Mắt Lưới: 100% Po...,"Không giặt, Không giặt khô, Không sấy khô",478321,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
3,accessories,https://www.uniqlo.com/vn/vi/products/E483050-000,Túi Dây Rút,Nữ,One Size,588000,5.0,8,NỮ One Size Túi Dây Rút VND 588.000 New 5.0 (8),Shell: Vải Túi Trong: 100% Polyeste/ Lớp Lót: ...,"Không giặt, Không giặt khô, Không sấy khô",483050,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
4,accessories,https://www.uniqlo.com/vn/vi/products/E481663-000,Túi Puffy,Nữ,One Size,588000,4.6,5,NỮ One Size Túi Puffy VND 588.000 New 4.6 (5),Shell: 100% Polyeste/ Lớp Độn: 100% Polyeste/ ...,"Không giặt, Không giặt khô, Không sấy khô",481663,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
414,innerwear,https://www.uniqlo.com/vn/vi/products/E482732-000,Tất Cổ Ngắn | 3 Đôi | Lót Lông,Nữ,23-25cm,195000,5.0,7,NỮ 23-25cm Tất Cổ Ngắn | 3 Đôi | Lót Lông VND ...,"44% Acrylic, 30% Bông, 22% Polyeste, 3% Elasta...","Giặt máy nước lạnh, Không giặt khô, Không sấy khô",482732,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
415,innerwear,https://www.uniqlo.com/vn/vi/products/E482730-000,Tất Cổ Ngắn | 3 Đôi,Nữ,23-25cm,195000,5.0,2,NỮ 23-25cm Tất Cổ Ngắn | 3 Đôi VND 195.000 5.0...,"65% Bông, 31% Nylon, 2% Polyeste, 2% Elastan","Giặt máy nước lạnh, Không giặt khô, Không sấy khô",482730,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
416,innerwear,https://www.uniqlo.com/vn/vi/products/E464384-000,Tất Cổ Ngắn | 3 Đôi | Thể Thao,Nữ,23-25cm,195000,4.8,111,NỮ 23-25cm Tất Cổ Ngắn | 3 Đôi | Thể Thao VND ...,Sản phẩm được tạo nên từ một trong những loại ...,"Giặt máy nước lạnh, Không giặt khô, Không sấy khô",482731,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
417,innerwear,https://www.uniqlo.com/vn/vi/products/E467421-000,NỮ TẤT,Nữ,23-25cm,195000,5.0,5,NỮ 23-25cm NỮ TẤT VND 195.000 New 5.0 (5),"82% Bông, 15% Polyeste, 2% Elastan, 1% Nylon","Giặt máy nước lạnh, Không giặt khô, Không sấy khô",482725,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
418,innerwear,https://www.uniqlo.com/vn/vi/products/E460431-000,Tất | 3 Đôi | Vải Gân,Nữ,23-25cm,195000,5.0,4,NỮ 23-25cm Tất | 3 Đôi | Vải Gân VND 195.000 N...,"66% Bông, 17% Polyeste, 15% Nylon, 2% Elastan","Giặt máy nước lạnh, Không giặt khô, Không sấy khô",482724,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...

## ***Lấy ra những ID nào đã bị xóa đi để loại bỏ trong phần reviewer***

In [170]:
print(f"Số lượng dòng đã xóa không có đánh giá: {len(dropped_product_rate)}")
print("Danh sách Mã sản phẩm bị xóa do không có đánh giá:", dropped_product_rate)

Số lượng dòng đã xóa không có đánh giá: 66
Danh sách Mã sản phẩm bị xóa do không có đánh giá: [484719, 483301, 483001, 482250, 485473, '484968', '483913', '483755', '482652', '483754', '482654', '484929', 'E483870-000', '483880', 485714, 483007, 485224, 484607, 484769, 484492, 486830, 484461, 485347, 482880, 482856, 484875, 484662, '482598', '482602', '483996', '482591', '485003', '485005', '482633', '485002', '482620', '482611', '482522', '482558', 482211, 484402, 481584, 482260, 484245, 485653, 485652, 485689, 482443, 482480, 482303, 484852, '483970', '481633', '485255', '485077', '484803', '485487', '487807', '485467', 482693, 482691, 482741, 485200, 485207, 482729, 482722]

In [171]:
print(f"Số lượng dòng đã xóa bị trùng lặp: {len(removed_product_duplicate)}")
print("Danh sách Mã sản phẩm bị trùng lặp:", removed_product_duplicate)

Số lượng dòng đã xóa bị trùng lặp: 448
Danh sách Mã sản phẩm bị trùng lặp: [478708, 480059, 485991, 484812, 482244, 478529, 482243, 478858, 482166, 482170, 483004, '478556', '487979', '479751', '478578', '484252', '478848', '481486', '478861', 'E478849-000', '478858', '478995', '478846', '478529', '483906', '483912', '482646', '473761', '473760', '481560', '482244', '483896', '482243', '479382', '481568', '481569', '484929', '483869', '483868', '475647', '479975', '479974', '482824', '482823', '483600', '481225', '481224', '480771', '480770', '480769', '480768', '480767', '480772', '476068', '482253', '482302', '483880', 479662, 483766, 480290, 476256, 485223, 481596, 481595, 482253, 482977, 478333, 484505, 480636, 479235, 478848, 482971, 483457, 485562, 476068, 482296, 485787, 476227, 477036, 473985, 484467, 484466, 483256, 484470, 484469, 483257, 484768, 484767, 483254, 484475, 484473, 484472, 483258, 478493, 478492, 478479, 479697, 484855, 482314, 482313, 479791, 479792, 479616, 480800, 479611, 480264, 485516, 484491, 484490, 483298, 486829, 486828, 486827, 486826, 483262, 484460, 484459, 483252, 484502, 484501, 484499, 484121, 484771, 484770, 481359, 478321, 481630, 481610, 479281, 479577, 484719, 484808, 479698, 482287, 479382, 484972, 482860, 481569, 479375, 479964, 481568, 479941, 479940, 479938, 482918, 476081, 482886, 482946, 470630, 483927, 474123, 481584, 482951, 477780, 482947, '479434', '471525', '479538', '479556', '480999', '474317', '482597', '474321', '482593', '482590', '482524', '479468', '482622', '482616', '482538', '484997', '487650', '482557', 479793, 484610, 479755, 475387, 478268, 480827, 487979, 481607, 481606, 482216, 478247, 482213, 478279, 478277, 482210, 485775, 482767, 478270, 478578, 484249, 483975, 481572, 479942, 479939, 481582, 485272, 482295, 480763, 480294, 485735, 482310, 481442, 481441, 482309, 484904, 480802, 479996, 484875, 484662, 476146, 482402, 482350, 482448, 485649, 484896, 484894, 484892, 482466, 482465, 480772, 484244, 484905, 484245, 482431, 474504, 481391, 482464, 482459, 480647, 480648, 485134, 485133, 485132, 481227, 481225, 481224, 480771, 480770, 480769, 480768, 480773, 480767, 478118, 485587, 486294, 482485, 474521, 483096, 483095, 479085, 485265, 484929, 484928, 483601, 479975, 479974, 475367, 482302, 485181, 485180, 484757, 481725, 482461, 482460, 485655, 482434, 482483, 482481, 482479, 483972, 482305, 478535, 481722, 481531, 485612, 482970, '481726', 'E475361-000', '482295', '482297', '482296', '482299', '485562', '479791', '479451', '485254', '485253', '484358', '487715', '486136', '486135', '486134', '486133', '482783', '484909', '484908', '482754', '485075', '485074', '485073', '482784', '485054', '485052', '485035', '485034', '485033', '482751', '485028', '485027', '482743', '485071', '485069', '485068', '485065', '485064', '482752', '480850', '474462', '480346', '480948', '480947', '480946', '480945', '480939', '477794', '477298', '477294', '479713', '479712', '479711', '477818', '477817', '477816', '477342', '475746', '478497', '478496', '478495', '478494', '478493', '478492', '478479', '479309', '477293', '482310', '482308', '482762', '482309', '485735', '482311', '482319', '476146', '475387', '482314', '482313', '484855', '479793', '479792', '479616', '487170', '487169', '487168', '487167', '487166', '485518', '480265', '480264', '485516', '479877', '479876', '479875', '479068', '472519', '485509', '479070', '468496', '479069', '471338', '471336', '466168', '471333', '479059', '479058', '485505', '459566', '471327', '479055', '471325', '471324', '471323', '471343', '471349', '457127', '471353', '471348', '471346', '471350', '471351', '471347', '471341', '471340', '471352', '471344', '485486', '485485', '482748', '487806', '487464', '487463', '486132', '486131', '484758', '482747', '485466', '485465', '482805', '483975', 482181, 482184, 478956, 480280, 481081, 478949, 478793, 480758, 478965, 469844, 480868, 480966, 479608, 482197, 482329, 473989, 482677, 482681, 482679, 480913, 484792, 482697, 482734, 484411, 484406, 482720, 482148, 484407]

In [172]:
removed_product_id = dropped_product_rate + removed_product_duplicate
print(f"Số lượng dòng đã xóa: {len(removed_product_id)}")
print("Danh sách Mã sản phẩm:", removed_product_id)

Số lượng dòng đã xóa: 514
Danh sách Mã sản phẩm: [484719, 483301, 483001, 482250, 485473, '484968', '483913', '483755', '482652', '483754', '482654', '484929', 'E483870-000', '483880', 485714, 483007, 485224, 484607, 484769, 484492, 486830, 484461, 485347, 482880, 482856, 484875, 484662, '482598', '482602', '483996', '482591', '485003', '485005', '482633', '485002', '482620', '482611', '482522', '482558', 482211, 484402, 481584, 482260, 484245, 485653, 485652, 485689, 482443, 482480, 482303, 484852, '483970', '481633', '485255', '485077', '484803', '485487', '487807', '485467', 482693, 482691, 482741, 485200, 485207, 482729, 482722, 478708, 480059, 485991, 484812, 482244, 478529, 482243, 478858, 482166, 482170, 483004, '478556', '487979', '479751', '478578', '484252', '478848', '481486', '478861', 'E478849-000', '478858', '478995', '478846', '478529', '483906', '483912', '482646', '473761', '473760', '481560', '482244', '483896', '482243', '479382', '481568', '481569', '484929', '483869', '483868', '475647', '479975', '479974', '482824', '482823', '483600', '481225', '481224', '480771', '480770', '480769', '480768', '480767', '480772', '476068', '482253', '482302', '483880', 479662, 483766, 480290, 476256, 485223, 481596, 481595, 482253, 482977, 478333, 484505, 480636, 479235, 478848, 482971, 483457, 485562, 476068, 482296, 485787, 476227, 477036, 473985, 484467, 484466, 483256, 484470, 484469, 483257, 484768, 484767, 483254, 484475, 484473, 484472, 483258, 478493, 478492, 478479, 479697, 484855, 482314, 482313, 479791, 479792, 479616, 480800, 479611, 480264, 485516, 484491, 484490, 483298, 486829, 486828, 486827, 486826, 483262, 484460, 484459, 483252, 484502, 484501, 484499, 484121, 484771, 484770, 481359, 478321, 481630, 481610, 479281, 479577, 484719, 484808, 479698, 482287, 479382, 484972, 482860, 481569, 479375, 479964, 481568, 479941, 479940, 479938, 482918, 476081, 482886, 482946, 470630, 483927, 474123, 481584, 482951, 477780, 482947, '479434', '471525', '479538', '479556', '480999', '474317', '482597', '474321', '482593', '482590', '482524', '479468', '482622', '482616', '482538', '484997', '487650', '482557', 479793, 484610, 479755, 475387, 478268, 480827, 487979, 481607, 481606, 482216, 478247, 482213, 478279, 478277, 482210, 485775, 482767, 478270, 478578, 484249, 483975, 481572, 479942, 479939, 481582, 485272, 482295, 480763, 480294, 485735, 482310, 481442, 481441, 482309, 484904, 480802, 479996, 484875, 484662, 476146, 482402, 482350, 482448, 485649, 484896, 484894, 484892, 482466, 482465, 480772, 484244, 484905, 484245, 482431, 474504, 481391, 482464, 482459, 480647, 480648, 485134, 485133, 485132, 481227, 481225, 481224, 480771, 480770, 480769, 480768, 480773, 480767, 478118, 485587, 486294, 482485, 474521, 483096, 483095, 479085, 485265, 484929, 484928, 483601, 479975, 479974, 475367, 482302, 485181, 485180, 484757, 481725, 482461, 482460, 485655, 482434, 482483, 482481, 482479, 483972, 482305, 478535, 481722, 481531, 485612, 482970, '481726', 'E475361-000', '482295', '482297', '482296', '482299', '485562', '479791', '479451', '485254', '485253', '484358', '487715', '486136', '486135', '486134', '486133', '482783', '484909', '484908', '482754', '485075', '485074', '485073', '482784', '485054', '485052', '485035', '485034', '485033', '482751', '485028', '485027', '482743', '485071', '485069', '485068', '485065', '485064', '482752', '480850', '474462', '480346', '480948', '480947', '480946', '480945', '480939', '477794', '477298', '477294', '479713', '479712', '479711', '477818', '477817', '477816', '477342', '475746', '478497', '478496', '478495', '478494', '478493', '478492', '478479', '479309', '477293', '482310', '482308', '482762', '482309', '485735', '482311', '482319', '476146', '475387', '482314', '482313', '484855', '479793', '479792', '479616', '487170', '487169', '487168', '487167', '487166', '485518', '480265', '480264', '485516', '479877', '479876', '479875', '479068', '472519', '485509', '479070', '468496', '479069', '471338', '471336', '466168', '471333', '479059', '479058', '485505', '459566', '471327', '479055', '471325', '471324', '471323', '471343', '471349', '457127', '471353', '471348', '471346', '471350', '471351', '471347', '471341', '471340', '471352', '471344', '485486', '485485', '482748', '487806', '487464', '487463', '486132', '486131', '484758', '482747', '485466', '485465', '482805', '483975', 482181, 482184, 478956, 480280, 481081, 478949, 478793, 480758, 478965, 469844, 480868, 480966, 479608, 482197, 482329, 473989, 482677, 482681, 482679, 480913, 484792, 482697, 482734, 484411, 484406, 482720, 482148, 484407]

In [173]:
df

,category,product_url,Product Name,Gender,Size,Price,Rate,Number_of_rates,Description,Chất liệu,Hướng dẫn giặt,Mã sản phẩm,img_url
0,accessories,https://www.uniqlo.com/vn/vi/products/E481610-000,Túi Bán Nguyệt Mini Đeo Chéo,Unisex,One Size,293000,5.0,93,UNISEX One Size Túi Bán Nguyệt Mini Đeo Chéo V...,Vải Ngoài: 100% Nylon ( 100% Sử Dụng Sợi Nylon...,"Không giặt, Không giặt khô, Không sấy khô",481610,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
1,accessories,https://www.uniqlo.com/vn/vi/products/E481359-000,Ba Lô Đa Tính Năng,Unisex,One Size,1471000,5.0,5,UNISEX One Size Ba Lô Đa Tính Năng VND 1.471.0...,Vải Chính: Thân: Đế: 100% Polyeste/ Mắt Lưới: ...,"Không giặt, Không giặt khô, Không sấy khô",481359,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
2,accessories,https://www.uniqlo.com/vn/vi/products/E478321-000,Balo Nhiều Ngăn,Unisex,One Size,980000,5.0,64,UNISEX One Size Balo Nhiều Ngăn VND 980.000 5....,Vải Chính: Thân: 100% Nylon/ Mắt Lưới: 100% Po...,"Không giặt, Không giặt khô, Không sấy khô",478321,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
3,accessories,https://www.uniqlo.com/vn/vi/products/E483050-000,Túi Dây Rút,Nữ,One Size,588000,5.0,8,NỮ One Size Túi Dây Rút VND 588.000 New 5.0 (8),Shell: Vải Túi Trong: 100% Polyeste/ Lớp Lót: ...,"Không giặt, Không giặt khô, Không sấy khô",483050,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
4,accessories,https://www.uniqlo.com/vn/vi/products/E481663-000,Túi Puffy,Nữ,One Size,588000,4.6,5,NỮ One Size Túi Puffy VND 588.000 New 4.6 (5),Shell: 100% Polyeste/ Lớp Độn: 100% Polyeste/ ...,"Không giặt, Không giặt khô, Không sấy khô",481663,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
414,innerwear,https://www.uniqlo.com/vn/vi/products/E482732-000,Tất Cổ Ngắn | 3 Đôi | Lót Lông,Nữ,23-25cm,195000,5.0,7,NỮ 23-25cm Tất Cổ Ngắn | 3 Đôi | Lót Lông VND ...,"44% Acrylic, 30% Bông, 22% Polyeste, 3% Elasta...","Giặt máy nước lạnh, Không giặt khô, Không sấy khô",482732,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
415,innerwear,https://www.uniqlo.com/vn/vi/products/E482730-000,Tất Cổ Ngắn | 3 Đôi,Nữ,23-25cm,195000,5.0,2,NỮ 23-25cm Tất Cổ Ngắn | 3 Đôi VND 195.000 5.0...,"65% Bông, 31% Nylon, 2% Polyeste, 2% Elastan","Giặt máy nước lạnh, Không giặt khô, Không sấy khô",482730,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
416,innerwear,https://www.uniqlo.com/vn/vi/products/E464384-000,Tất Cổ Ngắn | 3 Đôi | Thể Thao,Nữ,23-25cm,195000,4.8,111,NỮ 23-25cm Tất Cổ Ngắn | 3 Đôi | Thể Thao VND ...,Sản phẩm được tạo nên từ một trong những loại ...,"Giặt máy nước lạnh, Không giặt khô, Không sấy khô",482731,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
417,innerwear,https://www.uniqlo.com/vn/vi/products/E467421-000,NỮ TẤT,Nữ,23-25cm,195000,5.0,5,NỮ 23-25cm NỮ TẤT VND 195.000 New 5.0 (5),"82% Bông, 15% Polyeste, 2% Elastan, 1% Nylon","Giặt máy nước lạnh, Không giặt khô, Không sấy khô",482725,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...
418,innerwear,https://www.uniqlo.com/vn/vi/products/E460431-000,Tất | 3 Đôi | Vải Gân,Nữ,23-25cm,195000,5.0,4,NỮ 23-25cm Tất | 3 Đôi | Vải Gân VND 195.000 N...,"66% Bông, 17% Polyeste, 15% Nylon, 2% Elastan","Giặt máy nước lạnh, Không giặt khô, Không sấy khô",482724,https://image.uniqlo.com/UQ/ST3/AsianCommon/im...

## ***Lưu file product***

In [174]:
df.to_csv("uniqlo_product.csv", index=False, encoding='utf-8-sig')

# ***User***

In [175]:
df_innerwear_reviewer = pd.read_csv('uniqlo_women_innerwear_reviews.csv', sep=';')
df_innerwear_reviewer.head()

,product_url,Product Name,Mã sản phẩm,Reviewer,Rating,Comment,Review Date,Gender,Age,Height,Weight,Shoe Size,Country
0,https://www.uniqlo.com/vn/vi/products/E457912-000,AIRism Áo Không Tay,482150,Pika,5 out of 5 stars,Sleeveless top,14/12/2025,Nữ,25 đến 34 tuổi,151 - 155cm,41 - 45kg,EU36,Johor
1,https://www.uniqlo.com/vn/vi/products/E457912-000,AIRism Áo Không Tay,482150,Thulieen,5 out of 5 stars,Tuyệt vời,10/12/2025,Nữ,25 đến 34 tuổi,156 - 160cm,51 - 55kg,EU36,Thành phố Hà Nội
2,https://www.uniqlo.com/vn/vi/products/E457912-000,AIRism Áo Không Tay,482150,Thu Trang,5 out of 5 stars,"Phải nói là đỉnh của chóp, mặc như không mặc luôn",05/12/2025,Nữ,20 đến 24 tuổi,161 - 165cm,51 - 55kg,EU39,Thành phố Hà Nội
3,https://www.uniqlo.com/vn/vi/products/E457912-000,AIRism Áo Không Tay,482150,Raine,5 out of 5 stars,AIRism Sleeveless Top,04/12/2025,Nữ,45 đến 54 tuổi,151 - 155cm,61 - 65kg,EU36,Sabah
4,https://www.uniqlo.com/vn/vi/products/E457912-000,AIRism Áo Không Tay,482150,Lani,5 out of 5 stars,My Daily Wear,04/12/2025,Nữ,45 đến 54 tuổi,NaN,56 - 60kg,EU37,Singapore

In [176]:
import pandas as pd

# Lấy danh sách các file bắt đầu bằng uniqlo_women_ và kết thúc .csv
files = ["uniqlo_women_accessories_reviews.csv",
         "uniqlo_women_bottoms_reviews.csv", 
         "uniqlo_women_outerwear_reviews.csv",
         "uniqlo_women_loungewear-and-homewear_reviews.csv",
         "uniqlo_women_shirts-and-blouses_reviews.csv",
         "uniqlo_women_skirts-and-dresses_reviews.csv",
         "uniqlo_women_sweaters-and-knitwear_reviews.csv",
         "uniqlo_women_t-shirts-sweat-and-fleece_reviews.csv",
         "uniqlo_men_accessories_reviews.csv", 
         "uniqlo_men_bottoms_reviews.csv", 
         "uniqlo_men_innerwear_reviews.csv", 
         "uniqlo_men_outerwear_reviews.csv",
         "uniqlo_men_loungewear-and-homewear_reviews.csv",
         "uniqlo_men_linen_reviews.csv",
         "uniqlo_men_special-collaboration_reviews.csv",
         "uniqlo_men_uv-protection_reviews.csv",
         "uniqlo_men_shirts-and-polo-shirts_reviews.csv",
         "uniqlo_men_sweaters-and-knitwear_reviews.csv",
         "uniqlo_men_t-shirts-sweat-and-fleece_reviews.csv"]

# Đọc và gộp các file
df_list = [pd.read_csv(file) for file in files]
df_reviewer = pd.concat(df_list, ignore_index=True)
df_reviewer = pd.concat([df_reviewer, df_innerwear_reviewer], ignore_index=True)

df_reviewer.head()

,product_url,Product Name,Mã sản phẩm,Reviewer,Rating,Comment,Review Date,Gender,Age,Height,Weight,Shoe Size,Country
0,https://www.uniqlo.com/vn/vi/products/E481610-000,Túi Bán Nguyệt Mini Đeo Chéo,481610,Anna,5 out of 5 stars,Túi đẹp,20/12/2025,Nữ,NaN,NaN,NaN,NaN,Thành phố Hồ Chí Minh
1,https://www.uniqlo.com/vn/vi/products/E481610-000,Túi Bán Nguyệt Mini Đeo Chéo,481610,Abby,5 out of 5 stars,Handy and cute,20/12/2025,Nữ,25 đến 34 tuổi,NaN,NaN,NaN,Metro Manila
2,https://www.uniqlo.com/vn/vi/products/E481610-000,Túi Bán Nguyệt Mini Đeo Chéo,481610,-Loan Anh,5 out of 5 stars,Túi xách năng động,20/12/2025,Nữ,25 đến 34 tuổi,156 - 160cm,41 - 45kg,EU36,Thành phố Hồ Chí Minh
3,https://www.uniqlo.com/vn/vi/products/E481610-000,Túi Bán Nguyệt Mini Đeo Chéo,481610,misi,5 out of 5 stars,easy bag,20/12/2025,Nữ,NaN,NaN,NaN,NaN,Central Visayas
4,https://www.uniqlo.com/vn/vi/products/E481610-000,Túi Bán Nguyệt Mini Đeo Chéo,481610,Duty Bag?,5 out of 5 stars,Love this!,20/12/2025,Nữ,25 đến 34 tuổi,NaN,NaN,NaN,Metro Manila

In [177]:
df_reviewer

,product_url,Product Name,Mã sản phẩm,Reviewer,Rating,Comment,Review Date,Gender,Age,Height,Weight,Shoe Size,Country
0,https://www.uniqlo.com/vn/vi/products/E481610-000,Túi Bán Nguyệt Mini Đeo Chéo,481610,Anna,5 out of 5 stars,Túi đẹp,20/12/2025,Nữ,NaN,NaN,NaN,NaN,Thành phố Hồ Chí Minh
1,https://www.uniqlo.com/vn/vi/products/E481610-000,Túi Bán Nguyệt Mini Đeo Chéo,481610,Abby,5 out of 5 stars,Handy and cute,20/12/2025,Nữ,25 đến 34 tuổi,NaN,NaN,NaN,Metro Manila
2,https://www.uniqlo.com/vn/vi/products/E481610-000,Túi Bán Nguyệt Mini Đeo Chéo,481610,-Loan Anh,5 out of 5 stars,Túi xách năng động,20/12/2025,Nữ,25 đến 34 tuổi,156 - 160cm,41 - 45kg,EU36,Thành phố Hồ Chí Minh
3,https://www.uniqlo.com/vn/vi/products/E481610-000,Túi Bán Nguyệt Mini Đeo Chéo,481610,misi,5 out of 5 stars,easy bag,20/12/2025,Nữ,NaN,NaN,NaN,NaN,Central Visayas
4,https://www.uniqlo.com/vn/vi/products/E481610-000,Túi Bán Nguyệt Mini Đeo Chéo,481610,Duty Bag?,5 out of 5 stars,Love this!,20/12/2025,Nữ,25 đến 34 tuổi,NaN,NaN,NaN,Metro Manila
...,...,...,...,...,...,...,...,...,...,...,...,...,...
25620,https://www.uniqlo.com/vn/vi/products/E467421-000,NỮ TẤT,482725,Chloe,5 out of 5 stars,Thanks Uniqlo!,11/06/2025,Nữ,25 đến 34 tuổi,161 - 165cm,46 - 50kg,EU39,Kuala Lumpur
25621,https://www.uniqlo.com/vn/vi/products/E460431-000,Tất | 3 Đôi | Vải Gân,482724,Jasmine,5 out of 5 stars,Soft and comfortable,03/06/2025,Nữ,NaN,NaN,NaN,EU37,Singapore
25622,https://www.uniqlo.com/vn/vi/products/E460431-000,Tất | 3 Đôi | Vải Gân,482724,dorri,5 out of 5 stars,great quality,13/05/2025,Nữ,NaN,NaN,NaN,NaN,Singapore
25623,https://www.uniqlo.com/vn/vi/products/E460431-000,Tất | 3 Đôi | Vải Gân,482724,Dneo,5 out of 5 stars,Simple while socks,21/04/2025,Nữ,NaN,NaN,NaN,EU38,Singapore
25624,https://www.uniqlo.com/vn/vi/products/E484407-000,Tất | 3 Đôi,484407,Maymay,5 out of 5 stars,Nice and Comfy,10/12/2025,Nữ,25 đến 34 tuổi,NaN,NaN,NaN,Metro Manila

In [178]:
df_reviewer = df_reviewer.dropna()
df_reviewer = df_reviewer.reset_index(drop=True)
df_reviewer

,product_url,Product Name,Mã sản phẩm,Reviewer,Rating,Comment,Review Date,Gender,Age,Height,Weight,Shoe Size,Country
0,https://www.uniqlo.com/vn/vi/products/E481610-000,Túi Bán Nguyệt Mini Đeo Chéo,481610,-Loan Anh,5 out of 5 stars,Túi xách năng động,20/12/2025,Nữ,25 đến 34 tuổi,156 - 160cm,41 - 45kg,EU36,Thành phố Hồ Chí Minh
1,https://www.uniqlo.com/vn/vi/products/E481610-000,Túi Bán Nguyệt Mini Đeo Chéo,481610,Runa,5 out of 5 stars,A multifunction and multistyle shoulder bag,18/12/2025,Nữ,25 đến 34 tuổi,156 - 160cm,41 - 45kg,EU40,Central Java
2,https://www.uniqlo.com/vn/vi/products/E481610-000,Túi Bán Nguyệt Mini Đeo Chéo,481610,lily,5 out of 5 stars,"Túi bán nguyệt vừa nhỏ xinh, tiện lợi lại đựng...",17/12/2025,Nữ,20 đến 24 tuổi,161 - 165cm,51 - 55kg,EU37,Thành phố Hà Nội
3,https://www.uniqlo.com/vn/vi/products/E481610-000,Túi Bán Nguyệt Mini Đeo Chéo,481610,-,5 out of 5 stars,Túi đa năng,13/12/2025,Nữ,20 đến 24 tuổi,166 - 170cm,61 - 65kg,EU38,Thành phố Hà Nội
4,https://www.uniqlo.com/vn/vi/products/E481610-000,Túi Bán Nguyệt Mini Đeo Chéo,481610,myphuong,5 out of 5 stars,Tiện dụng,13/12/2025,Nữ,25 đến 34 tuổi,51 - 60cm,36 - 40kg,EU36,Thành phố Hồ Chí Minh
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12468,https://www.uniqlo.com/vn/vi/products/E464384-000,Tất Cổ Ngắn | 3 Đôi | Thể Thao,482731,ying,4 out of 5 stars,comfy,13/03/2025,Nữ,35 đến 44 tuổi,171 - 175cm,86 - 90kg,EU42,Sabah
12469,https://www.uniqlo.com/vn/vi/products/E464384-000,Tất Cổ Ngắn | 3 Đôi | Thể Thao,482731,Mary,5 out of 5 stars,Best purchase of the month,02/03/2025,Nữ,25 đến 34 tuổi,166 - 170cm,76 - 80kg,EU39,JABODETABEK
12470,https://www.uniqlo.com/vn/vi/products/E464384-000,Tất Cổ Ngắn | 3 Đôi | Thể Thao,482731,Faradithy,5 out of 5 stars,Worth to buy!,15/02/2025,Nữ,25 đến 34 tuổi,151 - 155cm,66 - 70kg,EU39,JABODETABEK
12471,https://www.uniqlo.com/vn/vi/products/E464384-000,Tất Cổ Ngắn | 3 Đôi | Thể Thao,482731,Karen,5 out of 5 stars,VERY COMFORTABLE,06/02/2025,Nữ,55 đến 64 tuổi,161 - 165cm,76 - 80kg,EU39,Singapore
12472,https://www.uniqlo.com/vn/vi/products/E467421-000,NỮ TẤT,482725,Chloe,5 out of 5 stars,Thanks Uniqlo!,11/06/2025,Nữ,25 đến 34 tuổi,161 - 165cm,46 - 50kg,EU39,Kuala Lumpur

In [179]:
df_reviewer = df_reviewer[~df_reviewer['Mã sản phẩm'].isin(removed_product_id)]
df_reviewer = df_reviewer.reset_index(drop=True)
df_reviewer

,product_url,Product Name,Mã sản phẩm,Reviewer,Rating,Comment,Review Date,Gender,Age,Height,Weight,Shoe Size,Country
0,https://www.uniqlo.com/vn/vi/products/E483050-000,Túi Dây Rút,483050,Pinkpink,5 out of 5 stars,True to size,15/12/2025,Nữ,25 đến 34 tuổi,141 - 150cm,56 - 60kg,EU36,Penang
1,https://www.uniqlo.com/vn/vi/products/E481663-000,Túi Puffy,481663,Syifa,5 out of 5 stars,Love it,20/12/2025,Nữ,20 đến 24 tuổi,156 - 160cm,46 - 50kg,EU41,Penang
2,https://www.uniqlo.com/vn/vi/products/E481663-000,Túi Puffy,481663,Yong,4 out of 5 stars,More inner pockets!,14/12/2025,Nam,20 đến 24 tuổi,181 - 185cm,71 - 75kg,EU45,Johor
3,https://www.uniqlo.com/vn/vi/products/E481663-000,Túi Puffy,481663,ahbii,5 out of 5 stars,bag,11/12/2025,Nữ,20 đến 24 tuổi,166 - 170cm,56 - 60kg,EU37,Penang
4,https://www.uniqlo.com/vn/vi/products/E474481-000,Quần Dài Siêu Co Giãn Dáng Rộng,483291,Lulu,5 out of 5 stars,Versatile pants for any occasion,13/12/2025,Nữ,35 đến 44 tuổi,156 - 160cm,66 - 70kg,EU39,Kuala Lumpur
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4938,https://www.uniqlo.com/vn/vi/products/E464384-000,Tất Cổ Ngắn | 3 Đôi | Thể Thao,482731,ying,4 out of 5 stars,comfy,13/03/2025,Nữ,35 đến 44 tuổi,171 - 175cm,86 - 90kg,EU42,Sabah
4939,https://www.uniqlo.com/vn/vi/products/E464384-000,Tất Cổ Ngắn | 3 Đôi | Thể Thao,482731,Mary,5 out of 5 stars,Best purchase of the month,02/03/2025,Nữ,25 đến 34 tuổi,166 - 170cm,76 - 80kg,EU39,JABODETABEK
4940,https://www.uniqlo.com/vn/vi/products/E464384-000,Tất Cổ Ngắn | 3 Đôi | Thể Thao,482731,Faradithy,5 out of 5 stars,Worth to buy!,15/02/2025,Nữ,25 đến 34 tuổi,151 - 155cm,66 - 70kg,EU39,JABODETABEK
4941,https://www.uniqlo.com/vn/vi/products/E464384-000,Tất Cổ Ngắn | 3 Đôi | Thể Thao,482731,Karen,5 out of 5 stars,VERY COMFORTABLE,06/02/2025,Nữ,55 đến 64 tuổi,161 - 165cm,76 - 80kg,EU39,Singapore
4942,https://www.uniqlo.com/vn/vi/products/E467421-000,NỮ TẤT,482725,Chloe,5 out of 5 stars,Thanks Uniqlo!,11/06/2025,Nữ,25 đến 34 tuổi,161 - 165cm,46 - 50kg,EU39,Kuala Lumpur

In [180]:
df_reviewer.to_csv("uniqlo_review.csv", index=False, encoding='utf-8-sig')

In [181]:
df_reviewer[df_reviewer['Reviewer'] == "-"]

,product_url,Product Name,Mã sản phẩm,Reviewer,Rating,Comment,Review Date,Gender,Age,Height,Weight,Shoe Size,Country
24,https://www.uniqlo.com/vn/vi/products/E474481-000,Quần Dài Siêu Co Giãn Dáng Rộng,483291,-,5 out of 5 stars,Chất liệu phù hợp thời tiết,11/10/2025,Nữ,35 đến 44 tuổi,161 - 165cm,56 - 60kg,EU37,Thành phố Hồ Chí Minh
43,https://www.uniqlo.com/vn/vi/products/E475820-000,Quần Dài Gear,475820,-,5 out of 5 stars,Đẹp vô cùnggg,05/12/2025,Nữ,25 đến 34 tuổi,156 - 160cm,56 - 60kg,EU36,Thành phố Hà Nội
49,https://www.uniqlo.com/vn/vi/products/E475820-000,Quần Dài Gear,475820,-,5 out of 5 stars,Quần mặc thoải mái đẹp,30/11/2025,Nữ,35 đến 44 tuổi,156 - 160cm,66 - 70kg,EU37,Khánh Hòa
50,https://www.uniqlo.com/vn/vi/products/E475820-000,Quần Dài Gear,475820,-,5 out of 5 stars,"Vải mềm, mặc thoải mái, dáng đẹp",29/11/2025,Nữ,35 đến 44 tuổi,156 - 160cm,46 - 50kg,EU38,Đồng Nai
65,https://www.uniqlo.com/vn/vi/products/E472485-000,Quần Jeans Dáng Rộng,483813,-,5 out of 5 stars,Quần jeans,20/12/2025,Nữ,25 đến 34 tuổi,151 - 155cm,41 - 45kg,EU35,Thành phố Hồ Chí Minh
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4906,https://www.uniqlo.com/vn/vi/products/E464390-000,Tất Ẩn | 3 Đôi | Vải Mắt Lưới,482737,-,5 out of 5 stars,very comfortable socks,16/04/2024,Nữ,35 đến 44 tuổi,161 - 165cm,61 - 65kg,EU37,Singapore
4915,https://www.uniqlo.com/vn/vi/products/E482732-000,Tất Cổ Ngắn | 3 Đôi | Lót Lông,482732,-,5 out of 5 stars,Tất đẹp cho nữ,08/12/2025,Nữ,15 đến 19 tuổi,161 - 165cm,41 - 45kg,EU38,Vĩnh Phúc
4922,https://www.uniqlo.com/vn/vi/products/E464384-000,Tất Cổ Ngắn | 3 Đôi | Thể Thao,482731,-,5 out of 5 stars,Good quality and value to money,29/11/2025,Nam,25 đến 34 tuổi,176 - 180cm,71 - 75kg,EU42,Penang
4927,https://www.uniqlo.com/vn/vi/products/E464384-000,Tất Cổ Ngắn | 3 Đôi | Thể Thao,482731,-,5 out of 5 stars,Tất mắt cá chân,22/08/2025,Nữ,35 đến 44 tuổi,141 - 150cm,51 - 55kg,EU36,Thành phố Hồ Chí Minh
4936,https://www.uniqlo.com/vn/vi/products/E464384-000,Tất Cổ Ngắn | 3 Đôi | Thể Thao,482731,-,5 out of 5 stars,Good to wear,08/05/2025,Nam,25 đến 34 tuổi,171 - 175cm,66 - 70kg,EU42,Kuala Lumpur

In [182]:
df_reviewer[df_reviewer['Reviewer'] == "-"].to_csv("demo.csv", index = False, encoding = "utf-8-sig")

## ***Xử lý thuộc tính Reviewer còn những chỗ để -***

In [183]:
df_reviewer[df_reviewer['Reviewer'] == "-"]['Product Name'].unique()

array(['Quần Dài Siêu Co Giãn Dáng Rộng', 'Quần Dài Gear',
       'Quần Jeans Dáng Rộng', 'Quần Jeans Ống Loe Rộng Dáng Rũ',
       'Quần Culottes Vải Nylon', 'Quần Jeans Dáng Ôm Ống Loe',
       'Quần Cotton Dáng Relax Dài Đến Mắt Cá | Denim',
       'Quần Cotton Dáng Relax Dài Đến Mắt Cá',
       'AIRism Quần Jogger Siêu Co Giãn', 'Quần Easy Vải Pha Linen',
       'Quần Dài Vải Dạ | Gingham', 'Quần Dài Vải Dạ | Caro',
       'Quần Cotton Dáng Relax Dài Đến Mắt Cá | Vải Denim',
       'Quần Smart Pants Ống Loe', 'Quần Easy Shorts Vải Cotton | Denim',
       'Quần Easy Shorts Vải Cotton', 'AIRism Quần Leggings Mềm Ống Loe',
       'Quần Giữ Ấm', 'AIRism Áo Hoodie Chống Tia UV Vải Mắt Lưới',
       'Áo Khoác Chống Tia UV Bỏ Túi', 'PUFFTECH Áo Khoác Chần Bông',
       'Áo Khoác Hai Mặt',
       'AIRism Áo Hoodie Chống Tia UV Kéo Khóa | Họa Tiết',
       'Áo Parka Hai Mặt', 'PUFFTECH Áo Khoác Chần Bông | Có Mũ',
       'Áo Khoác Giả Lông Cừu Hai Mặt Cản Gió',
       'Áo Khoác Kéo Khóa Dáng Ngắn', 'Áo Khoác Dáng Ngắn Kéo Khóa',
       'Áo Khoác Cản Gió', 'Áo Khoác Bomber', 'Áo Khoác Blouson Kéo Khóa',
       'Áo Khoác Cản Gió Cổ Trụ', 'Áo Khoác Blouson Dáng Ngắn Kéo Khóa',
       'Áo Parka Chắn Gió', 'Hybrid Down Áo Parka',
       'Áo Khoác Giả Lông Cừu Loại Dày Kéo Khóa',
       'PUFFTECH Áo Gi Lê Chần Bông Dáng Lửng',
       'PUFFTECH Áo Gile Chần Bông', 'Seamless Down Áo Parka Lông Vũ',
       'Seamless Down Áo Khoác | Có Mũ', 'Áo Kiểu Vải Rayon | Kẻ Sọc',
       'Áo Kiểu Vải Rayon', 'Áo Sơ Mi Vải Linen Cao Cấp',
       'Áo Sơ Mi Vải Cotton | Kẻ Sọc', 'Áo Sơ Mi Vải Cotton',
       'Áo Khoác Vải Cotton Cổ Trụ',
       'Áo Kiểu Vải Rayon Cổ Mở | Tay Lửng 3/4',
       'Áo Sơ Mi Dáng Boxy Vải Nylon Dáng Ngắn | Tay Lỡ',
       'Áo Sơ Mi Vải Pha Linen Cổ Mở | Kẻ Sọc', 'Áo Polo Mini',
       'Chân Váy Vải Chiffon Xếp Tầng | Họa Tiết', 'Chân Váy Vải Satin',
       'Chân Váy Vải Cotton Xếp Nếp | Họa Tiết',
       'Chân Váy Vải Cotton Xếp Nếp', 'Chân Váy Xếp Tầng',
       'Chân Váy Cocoon Vải Pha Cotton',
       'AIRism Cotton Đầm Thun Dáng Xòe',
       'AIRism Đầm Polo Mềm | Không Tay', 'Áo Len Cashmere Cổ Tròn',
       'Áo Cardigan Len Sợi Souffle Kéo Khóa',
       'Áo Len Sợi Souffle Cổ Tròn',
       'Áo Cardigan Vải Merino Gân Dáng Ngắn | Kẻ Sọc',
       'Áo Cardigan Len Merino Cổ Tròn',
       'Áo Cardigan Len Vặn Thừng Cổ Tròn',
       'Áo Cardigan Chống Tia UV Cổ Tròn | Kẻ Sọc',
       'Áo Cardigan Chống Tia UV Cổ Tròn', 'Áo Polo Vải Len Pha',
       'AIRism Cotton Áo Thun', 'AIRism Áo Thun Không Đường May',
       'Áo Thun Cổ Tròn', 'Áo Thun Mini',
       'Áo Thun Vải Slub Cotton | Raglan', 'Áo Thun Vải Gân Mềm',
       'Áo Thun Vải Gân Mềm | Kẻ Sọc',
       'Áo Giả Lông Cừu Đan Len Mềm Cổ Tròn',
       'Áo Thun Slub Jersey | Cổ V', 'Áo Thun Vải Waffle Dry Cổ Henley',
       'SUPIMA COTTON Áo Thun Cổ Tròn', 'UT Sanrio Characters Áo Thun',
       'UT NY POP ART Áo Thun | Basquiat', 'Áo Hoodie Nỉ Kéo Khóa',
       'Áo Nỉ', 'PEACE FOR ALL Áo Thun Ngắn Tay (Saul Leiter)',
       'PEACE FOR ALL Áo Thun | Moomin',
       'PEACE FOR ALL Áo Thun | Herzog & de Meuron',
       'PEACE FOR ALL Áo Thun | Ultraman',
       'PEACE FOR ALL (F. Risso) Áo Thun Ngắn Tay',
       'PEACE FOR ALL (Keith Haring) Áo Thun Ngắn Tay',
       'PEACE FOR ALL (Daido Moriyama) Áo Thun Ngắn Tay',
       'PEACE FOR ALL (PEANUTS) Áo Thun Ngắn Tay',
       'PEACE FOR ALL (Wim Wenders) Áo Thun Ngắn Tay',
       'PEACE FOR ALL (Dick Bruna) Áo Thun Ngắn Tay',
       'PEACE FOR ALL Lisa Larson Áo Thun Ngắn Tay',
       'PEACE FOR ALL (Akamai Technologies) Áo Thun Ngắn Tay',
       'PEACE FOR ALL (Christophe Lemaire) Áo Thun Ngắn Tay',
       'PEACE FOR ALL (Kashiwa Sato) Áo Thun Ngắn Tay',
       'PEACE FOR ALL (Rei Inamoto) Áo Thun Ngắn Tay',
       'PEACE FOR ALL (Shingo Kunieda) Áo Thun Ngắn Tay',
       'PEACE FOR ALL Áo Thun | Shinya Yamanaka',
       'PEACE FOR ALL Haruki Murakami Áo Thun Ngắn Tay',
       'Quần Jeans Ống Suông Dáng Rộng', 'Quần Chino Dáng Slim Fit',
       'Quần Jeans Siêu Co Giãn Nhiều Màu',
       'Quần Dài Vải Pha Linen Dáng Relax',
       'Quần Jogger Thể Thao Siêu Co Giãn',
       'Quần Smart Pants Dài Đến Mắt Cá | Vải Wool-like',
       'Quần Smart Pants Dài Đến Mắt Cá | Cotton',
       'Quần Dài Siêu Co Giãn', 'AirSense Quần Dài | Vải Wool-like',
       'Quần Shorts Thể Thao Siêu Co Giãn',
       'HEATTECH Ultra Warm Quần Tất Giữ Nhiệt',
       'HEATTECH Extra Warm Quần Tất Giữ Nhiệt',
       'HEATTECH Quần Tất Giữ Nhiệt',
       'HEATTECH Extra Warm Cotton Quần Tất Giữ Nhiệt',
       'HEATTECH Áo Giữ Nhiệt', 'HEATTECH Extra Warm Cotton Áo Giữ Nhiệt',
       'HEATTECH Extra Warm Áo Thun Giữ Nhiệt Vải Pha Cashmere Cổ Lọ',
       'HEATTECH Extra Warm Áo Thun Len Cashmere Cổ Tròn',
       'HEATTECH Ultra Warm Áo Thun Giữ Nhiệt Cổ Lọ',
       'HEATTECH Ultra Warm Áo Thun Giữ Nhiệt Cổ Tròn',
       'HEATTECH Tất Lửng Giữ Nhiệt | Lót Lông',
       'HEATTECH Tất Giữ Nhiệt | Wide Ribbed', 'HEATTECH Tất | Melange',
       'HEATTECH Tất | Fluffy', 'HEATTECH Tất | Waffle', 'TẤT HEATTECH',
       'Quần Trunks | Broadcloth',
       'AIRism Quần Lót Boxer Brief Không Đường May | Họa Tiết',
       'AIRism Quần Lót Boxer Briefs Không Đường May',
       'AIRism Áo Thun | Cổ Tròn', 'AIRism Áo Thun | Cổ V',
       'AIRism Áo Ba Lỗ Vải Mắt Lưới', 'Tất Cổ Thấp | Middle cut',
       'Tất Cổ Thấp | Lót Lông', 'Tất Cổ Ngắn | Melange',
       'Tất Cổ Ngắn | Layered', 'Tất Cổ Ngắn | Vải Gân',
       'Tất Cổ Ngắn | Vải Mắt Lưới | Họa Tiết', 'Tất Lửng',
       'Tất Lửng | Lót Lông', 'Tất | Lót Lông',
       'Tất Cổ Trung Vải Pile Mềm', 'Tất | Caro',
       'SUPIMA COTTON Tất | Wide Ribbed', 'Tất | Argyle',
       'SUPIMA COTTON Tất | Vải Pique', 'Tất 50 Màu',
       'AirSense Áo Khoác | Vải Wool-like',
       'PUFFTECH Áo Khoác | Non-Quilted',
       'Áo Sơ Mi Không Cần Ủi Dáng Ôm | Kẻ Sọc',
       'Áo Sơ Mi Không Cần Ủi | Kẻ Sọc', 'Áo Sơ Mi Không Cần Ủi Dáng Ôm',
       'Áo Sơ Mi Không Cần Ủi | Cổ Bẻ Rộng', 'Áo Sơ Mi Không Cần Ủi',
       'Áo Sơ Mi Không Cần Ủi | Button Down',
       'Áo Sơ Mi Vải Oxford Dáng Ôm | Kẻ Sọc',
       'Áo Sơ Mi Cổ Mở Vải Modal Cotton| Họa Tiết',
       'Áo Sơ Mi Cổ Mở Vải Modal Cotton',
       'Áo Len Sợi Souffle Cổ Kéo Khóa',
       'Áo Cardigan Dáng Sơ Mi Vải Milano Gân',
       'Áo Thun Milano Vải Gân Có Thể Giặt Máy',
       'Áo Len Cashmere Cổ Tròn Dài Tay', 'Áo Thun Dry Cổ Tròn Nhiều Màu',
       'DRY-EX Áo Thun | Hoạ Tiết', 'DRY-EX Áo Thun Cổ Tròn',
       'UT NY POP ART Áo Thun | Keith Haring', 'UT STUDIO GHIBLI Áo Thun',
       'UNIQLO LOGO Áo Nỉ', 'AIRism Cotton Áo Thun Tích Hợp Bra Cổ Rộng',
       'AIRism Quần Lót Không Đường May | Cạp Cao',
       'AIRism Quần Lót Không Đường May | Hiphugger',
       'HEATTECH Áo Thun Giữ Nhiệt Cổ Tròn',
       'HEATTECH Extra Warm Áo Thun Giữ Nhiệt Len Pha Cashmere | Cổ Lọ',
       'HEATTECH Extra Warm Áo Thun Giữ Nhiệt Len Pha Cashmere | Cổ Tròn',
       'Áo Ngực Không Gọng | Dáng 3D', 'Áo Ngực Không Gọng | 3D Hold',
       'Áo Ngực Không Gọng | Co Giãn', 'Quần Lót | Cạp Cao | Tiny Flower',
       'Quần Lót | Cạp Cao | Small Flower', 'Quần Lót | Hiphugger',
       'Tất Ẩn | 3 Đôi | Dáng Khoét Sâu', 'Tất Ẩn | 3 Đôi | Vải Mắt Lưới',
       'Tất Cổ Ngắn | 3 Đôi | Lót Lông', 'Tất Cổ Ngắn | 3 Đôi | Thể Thao'],
      dtype=object)

In [184]:
df_reviewer[df_reviewer['Reviewer'] != "-"]

,product_url,Product Name,Mã sản phẩm,Reviewer,Rating,Comment,Review Date,Gender,Age,Height,Weight,Shoe Size,Country
0,https://www.uniqlo.com/vn/vi/products/E483050-000,Túi Dây Rút,483050,Pinkpink,5 out of 5 stars,True to size,15/12/2025,Nữ,25 đến 34 tuổi,141 - 150cm,56 - 60kg,EU36,Penang
1,https://www.uniqlo.com/vn/vi/products/E481663-000,Túi Puffy,481663,Syifa,5 out of 5 stars,Love it,20/12/2025,Nữ,20 đến 24 tuổi,156 - 160cm,46 - 50kg,EU41,Penang
2,https://www.uniqlo.com/vn/vi/products/E481663-000,Túi Puffy,481663,Yong,4 out of 5 stars,More inner pockets!,14/12/2025,Nam,20 đến 24 tuổi,181 - 185cm,71 - 75kg,EU45,Johor
3,https://www.uniqlo.com/vn/vi/products/E481663-000,Túi Puffy,481663,ahbii,5 out of 5 stars,bag,11/12/2025,Nữ,20 đến 24 tuổi,166 - 170cm,56 - 60kg,EU37,Penang
4,https://www.uniqlo.com/vn/vi/products/E474481-000,Quần Dài Siêu Co Giãn Dáng Rộng,483291,Lulu,5 out of 5 stars,Versatile pants for any occasion,13/12/2025,Nữ,35 đến 44 tuổi,156 - 160cm,66 - 70kg,EU39,Kuala Lumpur
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4938,https://www.uniqlo.com/vn/vi/products/E464384-000,Tất Cổ Ngắn | 3 Đôi | Thể Thao,482731,ying,4 out of 5 stars,comfy,13/03/2025,Nữ,35 đến 44 tuổi,171 - 175cm,86 - 90kg,EU42,Sabah
4939,https://www.uniqlo.com/vn/vi/products/E464384-000,Tất Cổ Ngắn | 3 Đôi | Thể Thao,482731,Mary,5 out of 5 stars,Best purchase of the month,02/03/2025,Nữ,25 đến 34 tuổi,166 - 170cm,76 - 80kg,EU39,JABODETABEK
4940,https://www.uniqlo.com/vn/vi/products/E464384-000,Tất Cổ Ngắn | 3 Đôi | Thể Thao,482731,Faradithy,5 out of 5 stars,Worth to buy!,15/02/2025,Nữ,25 đến 34 tuổi,151 - 155cm,66 - 70kg,EU39,JABODETABEK
4941,https://www.uniqlo.com/vn/vi/products/E464384-000,Tất Cổ Ngắn | 3 Đôi | Thể Thao,482731,Karen,5 out of 5 stars,VERY COMFORTABLE,06/02/2025,Nữ,55 đến 64 tuổi,161 - 165cm,76 - 80kg,EU39,Singapore
4942,https://www.uniqlo.com/vn/vi/products/E467421-000,NỮ TẤT,482725,Chloe,5 out of 5 stars,Thanks Uniqlo!,11/06/2025,Nữ,25 đến 34 tuổi,161 - 165cm,46 - 50kg,EU39,Kuala Lumpur

### ***Bỏ đi những cái tên - và xem xét nếu như số lượng Reviewer trong từng Mã sản phẩm như nào rồi xử lý nó***

In [185]:
products_info = df_reviewer.loc[df_reviewer['Reviewer'].eq('-'), ['Product Name', 'Mã sản phẩm']]
tong = 0

lost_review_product_ids = []
for index, row in products_info.iterrows():
    prod_name = row['Product Name']
    prod_id = row['Mã sản phẩm']
    
    mask = df_reviewer['Mã sản phẩm'].eq(prod_id) & df_reviewer['Reviewer'].ne('-')
    count = mask.sum()
    
    if count == 0:
        print(f"Mã: {prod_id} | Tên: {prod_name}")
        lost_review_product_ids.append(prod_id)
    tong += count
    

print(f"---")
print(f"Tong: {tong}")

Mã: 484471 | Tên: UT Sanrio Characters Áo Thun
Mã: 483925 | Tên: AIRism Cotton Áo Thun Tích Hợp Bra Cổ Rộng
---
Tong: 11252

In [186]:
lost_review_product_ids

[484471, 483925]

In [187]:
df_reviewer = df_reviewer[df_reviewer['Reviewer'] != "-"]
df_reviewer = df_reviewer.reset_index(drop=True)

In [188]:
remove_id = removed_product_id + lost_review_product_ids
len(remove_id)

516

In [189]:
df_reviewer

,product_url,Product Name,Mã sản phẩm,Reviewer,Rating,Comment,Review Date,Gender,Age,Height,Weight,Shoe Size,Country
0,https://www.uniqlo.com/vn/vi/products/E483050-000,Túi Dây Rút,483050,Pinkpink,5 out of 5 stars,True to size,15/12/2025,Nữ,25 đến 34 tuổi,141 - 150cm,56 - 60kg,EU36,Penang
1,https://www.uniqlo.com/vn/vi/products/E481663-000,Túi Puffy,481663,Syifa,5 out of 5 stars,Love it,20/12/2025,Nữ,20 đến 24 tuổi,156 - 160cm,46 - 50kg,EU41,Penang
2,https://www.uniqlo.com/vn/vi/products/E481663-000,Túi Puffy,481663,Yong,4 out of 5 stars,More inner pockets!,14/12/2025,Nam,20 đến 24 tuổi,181 - 185cm,71 - 75kg,EU45,Johor
3,https://www.uniqlo.com/vn/vi/products/E481663-000,Túi Puffy,481663,ahbii,5 out of 5 stars,bag,11/12/2025,Nữ,20 đến 24 tuổi,166 - 170cm,56 - 60kg,EU37,Penang
4,https://www.uniqlo.com/vn/vi/products/E474481-000,Quần Dài Siêu Co Giãn Dáng Rộng,483291,Lulu,5 out of 5 stars,Versatile pants for any occasion,13/12/2025,Nữ,35 đến 44 tuổi,156 - 160cm,66 - 70kg,EU39,Kuala Lumpur
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4452,https://www.uniqlo.com/vn/vi/products/E464384-000,Tất Cổ Ngắn | 3 Đôi | Thể Thao,482731,ying,4 out of 5 stars,comfy,13/03/2025,Nữ,35 đến 44 tuổi,171 - 175cm,86 - 90kg,EU42,Sabah
4453,https://www.uniqlo.com/vn/vi/products/E464384-000,Tất Cổ Ngắn | 3 Đôi | Thể Thao,482731,Mary,5 out of 5 stars,Best purchase of the month,02/03/2025,Nữ,25 đến 34 tuổi,166 - 170cm,76 - 80kg,EU39,JABODETABEK
4454,https://www.uniqlo.com/vn/vi/products/E464384-000,Tất Cổ Ngắn | 3 Đôi | Thể Thao,482731,Faradithy,5 out of 5 stars,Worth to buy!,15/02/2025,Nữ,25 đến 34 tuổi,151 - 155cm,66 - 70kg,EU39,JABODETABEK
4455,https://www.uniqlo.com/vn/vi/products/E464384-000,Tất Cổ Ngắn | 3 Đôi | Thể Thao,482731,Karen,5 out of 5 stars,VERY COMFORTABLE,06/02/2025,Nữ,55 đến 64 tuổi,161 - 165cm,76 - 80kg,EU39,Singapore
4456,https://www.uniqlo.com/vn/vi/products/E467421-000,NỮ TẤT,482725,Chloe,5 out of 5 stars,Thanks Uniqlo!,11/06/2025,Nữ,25 đến 34 tuổi,161 - 165cm,46 - 50kg,EU39,Kuala Lumpur

In [190]:
df = df[~df['Mã sản phẩm'].isin(remove_id)]
df = df.reset_index(drop = True)
print(f"Số dòng còn lại: {len(df)}")

Số dòng còn lại: 352

In [191]:
df.to_csv("uniqlo_product.csv", index=False, encoding='utf-8-sig')
df_reviewer.to_csv("uniqlo_review.csv", index=False, encoding='utf-8-sig')

In [192]:
len(df)

352

In [193]:
len(df_reviewer)

4457